version: '3.8'

services:
  fastapi-app:
    image: fastapi-whatsapp-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
